package db.dao;

import db.model.Products;
import db.model.ProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    long countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int insert(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int insertSelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    Products selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int updateByExampleSelective(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int updateByExample(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int updateByPrimaryKeySelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Tue Jan 17 22:09:07 MSK 2023
     */
    int updateByPrimaryKey(Products row);
}